spring:
  profiles:
    active: local
server:
  port: 8081

  
---
spring:
  profiles: local
  application:
   name: DEPARTMENT-SERVICE   #this name will use by service registery on erueka server ui  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: system
    password: Oracle1234
  jpa:
   hibernate.ddl-auto : update
   properties.hibernate.dialect: org.hibernate.dialect.OracleDialect
  
eureka: # Register with Eurekaserver
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: dev
  
  datasource:
    url: jdbc:h2:mem:testdb # you ca access h2 ui on  http://localhost:8088/h2-console/login.jsp?jsessionid=888c4a9dadcf173bb49afc2dba0a75e5
    driver-class-name: org.h2.Driver
#    data-username: sa
#    data-password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true